shallow_clone: true

platform:
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2017

cache:
  - C:\cmake-3.8.0-win32-x86
  - C:\local
  - C:\local\openblas

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.8.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.8/cmake-3.8.0-win32-x86.zip'
        7z x -y cmake-3.8.0-win32-x86.zip -oC:\
      }
      Invoke-WebRequest -Uri "https://sourceforge.net/projects/openblas/files/v0.3.7/OpenBLAS-0.3.7-x64.zip/download" -OutFile openblas.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
      Expand-Archive .\openblas.zip "C:\local\openblas"
      dir "C:\local\openblas"
      $env:PATH="C:\cmake-3.8.0-win32-x86\bin;C:\local\openblas\bin;$env:PATH"
before_build:
  - ps: |
      mkdir build
      cd build
      $env:generator="Visual Studio 15 2017 Win64"
      echo generator="$env:generator"
      cmake .. -G "$env:generator"
build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal

test_script:
  - ctest -C %CONFIGURATION% -j2

deploy: off