# based on github.com/Microsoft/GSL

shallow_clone: true

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2017

cache:
  - C:\cmake-3.8.0-win32-x86
  - C:\local

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.8.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.8/cmake-3.8.0-win32-x86.zip'
        7z x -y cmake-3.8.0-win32-x86.zip -oC:\
      }
      nuget install OpenBLAS -o "C:\local\"
      nuget install armadillo-code -o "C:\local\"
      $env:BOOST_ROOT="C:\Libraries\boost_1_67_0"
      $env:PATH="C:\cmake-3.8.0-win32-x86\bin;C:\local\OpenBLAS.0.2.14.1\lib\native\win32\bin;C:\local\OpenBLAS.0.2.14.1\lib\native\x64\bin;$env:PATH"

before_build:
  - ps: |
      mkdir build
      cd build
      $env:generator="Visual Studio 15 2017"
      if ($env:PLATFORM -eq "x64") {
          $env:generator="$env:generator Win64"
      }
      echo generator="$env:generator"
      cmake .. -G "$env:generator"

build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal

test_script:
  - ctest -C %CONFIGURATION% -j2

deploy: off
