# Makefile for building on *NIX systems.
 
SHELL = /bin/sh

#### Start of system configuration section ####

# Common installation prefix.
prefix = @prefix@

# Installation directory for executables.
bindir = $(prefix)/bin

# Installation directory for header files.
includedir = $(prefix)/include

# Installation directory for object code libraries.
libdir = $(prefix)/lib

# Armadillo library.
ifeq ($(shell uname -s), macos)
	ARMA_INC_PATH = -I/usr/local/include
	ARMA_LIB_PATH = -L/usr/local/lib
	ARMALIB = -larmadillo -framework Accelerate
else
	ARMA_INC_PATH = 
	ARMA_LIB_PATH = 
	ARMALIB = -larmadillo
endif

# Compiler settings.
CXX       = @cxx@
CXXFLAGS += @cxxflags@
CPPFLAGS  = -I. $(ARMA_INC_PATH) 
DEPFLAGS  = @cxx_depflag@
LDFLAGS  += $(ARMA_LIB_PATH) 
DEFS      = @defs@

# Do not build shared library on Cygwin.
ifneq ($(shell uname -s | sed -e s/\-.*//), CYGWIN_NT)
	CXXFLAGS += @cxx_shared_flag@ 
	LDFLAGS  += @cxx_shared_ldflag@
endif

ifeq ($(CXX), icpc)
	AR = xiar
else
	AR = ar
endif

.SUFFIXES:
.SUFFIXES: .cpp .h .d .o .a .so

#### End of system configuration section ####

LIBSHARED = libchem.so
LIBSTATIC = libchem.a

ifeq ($(shell uname -s | sed -e s/\-.*//), CYGWIN_NT)
	LIBCHEM = $(LIBSTATIC)
else
	LIBCHEM = $(LIBSHARED) $(LIBSTATIC)
endif

SRC :=	argparse.cpp input.cpp ptable.cpp datum.cpp molecule_io.cpp \
    	molecule.cpp molrot.cpp math.cpp zmatrix.cpp molvib.cpp
SRC := 	$(addprefix ./chem/,$(SRC))
OBJ := 	$(SRC:.cpp=.o)
HH  := 	$(shell ls ./chem/*.h)

LIBS =  $(ARMALIB)

.PHONY: all
all: $(LIBCHEM) apps

.PHONY: doc
doc:
	doxygen chemapps.cfg

.PHONY: apps
apps: 
	cd ./src && $(MAKE) all

.PHONY: tests
tests: all
	cd ./tests && $(MAKE) all

.PHONY: install
install: all
	if ! test -d $(DESTDIR)$(includedir)/chem ; then \
		mkdir $(DESTDIR)$(includedir)/chem ; \
	fi 
	if test -d $(DESTDIR)$(includedir)/chem ; then \
		for H in $(HH) ; do \
			cp -f $$H $(DESTDIR)$(includedir)/chem ; \
		done ; \
	fi  
	if test -d $(DESTDIR)$(libdir) ; then \
		cp -f $(LIBCHEM) $(DESTDIR)$(libdir) ; \
	fi 

.PHONY: uninstall
uninstall:
	rm -f $(DESTDIR)$(libdir)/$(LIBSHARED) 
	rm -f $(DESTDIR)$(libdir)/$(LIBSTATIC)
	for H in $(notdir $(HH)) ; do \
		rm -f $(DESTDIR)$(includedir)/chem/$$H ; \
	done 

.PHONY: clean
clean:
	rm -f $(LIBCHEM) $(OBJ) 
	cd ./src && $(MAKE) clean
	cd ./tests && $(MAKE) clean

.PHONY: distclean
distclean: clean
	rm -f *~ *.bak *.tmp *.stackdump core
	cd ./chem && rm -f *~ *.bak *.tmp *.d *.gch TAGS
	cd ./src && $(MAKE) distclean
	cd ./tests && $(MAKE) distclean
	cd ./html && rm -f *.*

.PHONY: TAGS
TAGS:
	etags ./chem/*.cpp ./chem/*.h
	etags ./src/*.cpp ./src/*.h

$(LIBSHARED): $(OBJ) 
	$(CXX) $(CXXFLAGS) $(DEFS) -o $@ $^ $(LDFLAGS) $(LIBS)

$(LIBSTATIC): $(OBJ)
	$(AR) rcs $@ $^

%.o : %.cpp
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(DEFS) -o $@ -c $< 

%.d : %.cpp
	$(CXX) $(DEPFLAGS) $(CPPFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	rm -f $@.$$$$

-include $(SRC:.cpp=.d) 

