parameters:
  jobName: ''
  imageName: ''

jobs:
- job:
  displayName: ${{ parameters.imageName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  strategy:
    matrix:
      debug:
        BUILD_TYPE: 'Debug'
      release:
        BUILD_TYPE: 'Release'
  continueOnError: false

  steps:
  - powershell: |
      Invoke-WebRequest -Uri "https://sourceforge.net/projects/openblas/files/v0.3.7/OpenBLAS-0.3.7-x64.zip/download" -OutFile openblas.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
      mkdir openblas
      Expand-Archive .\openblas.zip .\openblas
      Write-Host "##vso[task.setvariable variable=BLAS_DIR;]${env:System.DefaultWorkingDirectory}\openblas"
      Write-Host "Making ${env:BLAS_DIR} available as an environment variable."
    name: Prepare

  - powershell: echo ${env:BLAS_DIR}

#  - task: CMake@1
#    name: Configure
#    inputs:
#      workingDirectory: build
#      cmakeArgs: ' .. '
#
#  - task: CMake@1
#    name: Build
#    inputs:
#      workingDirectory: build
#      cmakeArgs: '--build . --config $(BUILD_TYPE)'
#
#  - script: ctest -C $(BUILD_TYPE) --output-on-failure --no-compress-output
#    name: CTest
#    workingDirectory: build
#    failOnStderr: true